name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:

env:
  SCHEME: NeverMiss

jobs:
  build:
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build
        run: |
          xcodebuild -scheme "$SCHEME" \
            -configuration Release \
            -destination 'generic/platform=macOS' \
            ARCHS="arm64 x86_64" \
            CODE_SIGNING_ALLOWED=NO \
            build
